"""create notes table

Revision ID: 1b98dcc78e6f
Revises: 08c744b89235
Create Date: 2022-05-03 16:51:40.014811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b98dcc78e6f'
down_revision = '08c744b89235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('notes', sa.Column('trip_id', sa.Integer(), nullable=False))
    op.add_column('notes', sa.Column('trip_date', sa.Date(), nullable=False))
    op.add_column('notes', sa.Column('note', sa.String(length=1000), nullable=False))
    op.add_column('notes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'created_at')
    op.drop_column('notes', 'note')
    op.drop_column('notes', 'trip_date')
    op.drop_column('notes', 'trip_id')
    op.drop_column('notes', 'owner_id')
    # ### end Alembic commands ###
