"""join table and updates

Revision ID: c50d11902748
Revises: 1b98dcc78e6f
Create Date: 2022-05-03 17:46:21.350757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50d11902748'
down_revision = '1b98dcc78e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_invites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'trip_id')
    )
    op.alter_column('events', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('events', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'events', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['owner_id'], ['id'])
    op.alter_column('notes', 'trip_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'notes', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'trips', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.alter_column('notes', 'trip_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('events', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_table('trip_invites')
    # ### end Alembic commands ###
