"""create events table

Revision ID: 08c744b89235
Revises: b9bf48b54a30
Create Date: 2022-05-03 16:34:15.461404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c744b89235'
down_revision = 'b9bf48b54a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('trip_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('events', sa.Column('description', sa.String(length=4000), nullable=False))
    op.add_column('events', sa.Column('image_url', sa.String(length=510), nullable=False))
    op.add_column('events', sa.Column('location', sa.String(length=255), nullable=False))
    op.add_column('events', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('events', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('trips', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('trips', 'updated_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('trips', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'start_date')
    op.drop_column('events', 'location')
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'description')
    op.drop_column('events', 'name')
    op.drop_column('events', 'trip_id')
    op.drop_column('events', 'owner_id')
    # ### end Alembic commands ###
