"""changed events. does this work?

Revision ID: 17daec0ac472
Revises: 452549a5125e
Create Date: 2022-06-28 13:07:33.561480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17daec0ac472'
down_revision = '452549a5125e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('lat', sa.Numeric(precision=15, scale=10), nullable=False))
    op.add_column('events', sa.Column('lng', sa.Numeric(precision=15, scale=10), nullable=False))
    op.alter_column('events', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('events', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('events', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('events', 'lng')
    op.drop_column('events', 'lat')
    # ### end Alembic commands ###
